### ISSUE TITLE
Rip out read_marcs_to_fv()

### ISSUE THREAD

**Issue by jvshields** [tardis-sn/stardis#115]
The new MARCS model reader makes the read_marcs_to_fv() function redundant. It also builds a physically incorrect model and should not be used going forward. Benchmarking and other parts of the code that use this function should change over to the model reader to construct a stellar model when [PR 112](https://github.com/tardis-sn/stardis/pull/112#issue-1840012563) gets merged.

**Comment by smokestacklightnin** [comment]
Perhaps in the meantime, we can at least add a [deprecation warning](https://stackoverflow.com/a/9008488)
