### ISSUE TITLE
Allow accessing opacity and broadening by source

### ISSUE THREAD

**Issue by isaacgsmith** [tardis-sn/stardis#32]
The `STARDISOutput` class should store information about the opacity and broadening by source -- i.e. something like `output.opacity.bf.H_I` should yield the `H I` bound-free opacity, and something like `output.broadening.gamma.quadratic_stark` should yield the quadratic stark broadening parameters.

**Comment by jvshields** [comment]
This has been implemented. Opacities are stored in a dictionary that are linked to by name.
