### ISSUE TITLE
Add molecules to the stellar plasma

### ISSUE THREAD

**Issue by isaacgsmith** [tardis-sn/stardis#62]
Many stars have molecules that are sources of both continuum and line opacity. We can currently only handle continuum opacity from H2, so the stellar plasma needs to be able to solve for the density of other molecules, and also include their lines (this would require several changes in how line opacity is handled).

**Comment by Jay-sanjay** [comment]
sir , can you tell where should the changes be made. I want to contribute to this issue

**Comment by jvshields** [comment]
First working implementation in PR #210
