### ISSUE TITLE
Combine documentation for Quickstart and Running the Code

### ISSUE THREAD

**Issue by smokestacklightnin** [tardis-sn/stardis#91]
Currently, the documentation has a [Running the Code](https://tardis-sn.github.io/stardis/running_the_code.html) section and a [Quickstart](https://tardis-sn.github.io/stardis/quickstart/quickstart.html) page that is converted automatically from [a Jupyter notebook](https://github.com/tardis-sn/stardis/blob/main/docs/quickstart/quickstart.ipynb). 

Quickstart contains no description of the code beyond a few comments, and Running the Code not only includes the writeup that the Quickstart is (in my opinion) missing, but also references Quickstart in multiple places.

I propose that we combine the two pages by taking the content from Running the Code and adding it to MarkDown cells in Quickstart. An alternative would be to import the Quickstart code into Running the Code, but that seems less natural to me.

**Comment by jvshields** [comment]
This sounds good to me. I don't see a reason to have the information live in two different places, and a fleshed out quickstart notebook that could just be the example for running the code makes sense.
